spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storage
    username: postgres
    password: Info@1234
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false

